import time
name = input("Numele tau este : ")
print(name + " e nume de prost")
time.sleep(1)
print("Nu cred ca stiai dar 1+1=2")
time.sleep(2)
print("NU esti amuzant, doar zi man")
time.sleep(2)
print("Stii bancul cu timpul??")
time.sleep(2)
lol = input("Stii dc nu te suport?? :")
time.sleep(2)
print(" pentru ca esti enervant")
time.sleep(3)
print("a si inca ceva fraiere ca nu pot sa cred ca imi iese")
time.sleep(2)
print("cat timp tu citesti asta se copie niste fisiere de pe local")
time.sleep(2)
print("Nu mai e mult")
time.sleep(2)
print("Loading files to Github.com")
time.sleep(4)
print("In progress...")
time.sleep(5)
print("Deci esti cam gata man, si nu incerca sa inchizi asta ca ti le sterge si tie si mie si le pierzi pe bune")
time.sleep(2)
print("normal le pastrezi dar si eu :)) dar daca inchizi asta nu")
time.sleep(2)
print("File transfer completed.")
time.sleep(9)
print("Hehe lol")
time.sleep(2)
print("ms de poze si parole boss")
time.sleep(2)
print(" te pup jos")
time.sleep(2)
sugi = input(" Mai vrei fisierele inapoi?")
time.sleep(2)
print("sugi")
